language: java

jdk:
  - oraclejdk8

script:
  - ./gradlew check distTar distZip

# Skip gradle assemble
# Refer to http://stackoverflow.com/questions/26566564/override-default-travis-ci-script-for-java-gradle-project
install: /bin/true
